import re
import sys

# Windows PowerShellでのUnicode出力対応
sys.stdout.reconfigure(encoding='utf-8')

# 公式のチャンピオン名マッピング（英語名 → 日本語名）
champion_mapping = {
    "Aatrox": "エイトロックス",
    "Ahri": "アーリ",
    "Akali": "アカリ",
    "Akshan": "アクシャン",
    "Alistar": "アリスター",
    "Ambessa": "アンベッサ",
    "Amumu": "アムム",
    "Anivia": "アニビア",
    "Annie": "アニー",
    "Aphelios": "アフェリオス",
    "Ashe": "アッシュ",
    "Aurelion Sol": "オレリオン・ソル",
    "Aurora": "オーロラ",
    "Azir": "アジール",
    "Bard": "バード",
    "Bel'Veth": "ベル＝ヴェス",
    "Blitzcrank": "ブリッツクランク",
    "Brand": "ブランド",
    "Braum": "ブラウム",
    "Briar": "ブライアー",
    "Caitlyn": "ケイトリン",
    "Camille": "カミール",
    "Cassiopeia": "カシオペア",
    "Cho'Gath": "チョ＝ガス",
    "Corki": "コーキ",
    "Darius": "ダリウス",
    "Diana": "ダイアナ",
    "Dr.Mundo": "ドクター・ムンド",
    "Draven": "ドレイヴン",
    "Ekko": "エコー",
    "Elise": "エリス",
    "Evelynn": "イブリン",
    "Ezreal": "エズリアル",
    "Fiddlesticks": "フィドルスティックス",
    "Fiora": "フィオラ",
    "Fizz": "フィズ",
    "Galio": "ガリオ",
    "Gangplank": "ガングプランク",
    "Garen": "ガレン",
    "Gnar": "ナー",
    "Gragas": "グラガス",
    "Graves": "グレイブス",
    "Gwen": "グウェン",
    "Hecarim": "ヘカリム",
    "Heimerdinger": "ハイマーディンガー",
    "Hwei": "フェイ",
    "Illaoi": "イラオイ",
    "Irelia": "イレリア",
    "Ivern": "アイバーン",
    "Janna": "ジャンナ",
    "Jarvan IV": "ジャーヴァンIV",
    "Jax": "ジャックス",
    "Jayce": "ジェイス",
    "Jhin": "ジン",
    "Jinx": "ジンクス",
    "Kai'Sa": "カイ＝サ",
    "Kalista": "カリスタ",
    "Karma": "カルマ",
    "Karthus": "カーサス",
    "Kassadin": "カサディン",
    "Katarina": "カタリナ",
    "Kayle": "ケイル",
    "Kayn": "ケイン",
    "Kennen": "ケネン",
    "Kha'Zix": "カ＝ジックス",
    "Kindred": "キンドレッド",
    "Kled": "クレッド",
    "Kog'Maw": "コグ＝マウ",
    "K'Sante": "カ・サンテ",
    "LeBlanc": "ルブラン",
    "Lee Sin": "リー・シン",
    "Leona": "レオナ",
    "Lillia": "リリア",
    "Lissandra": "リサンドラ",
    "Lucian": "ルシアン",
    "Lulu": "ルル",
    "Lux": "ラックス",
    "Malphite": "マルファイト",
    "Malzahar": "マルザハール",
    "Maokai": "マオカイ",
    "Master Yi": "マスター・イー",
    "Mel": "メル",
    "Milio": "ミリオ",
    "Miss Fortune": "ミス・フォーチュン",
    "Mordekaiser": "モルデカイザー",
    "Morgana": "モルガナ",
    "Naafiri": "ナフィーリ",
    "Nami": "ナミ",
    "Nasus": "ナサス",
    "Nautilus": "ノーチラス",
    "Neeko": "ニーコ",
    "Nidalee": "ニダリー",
    "Nilah": "ニーラ",
    "Nocturne": "ノクターン",
    "Nunu & Willump": "ヌヌ＆ウィルンプ",
    "Olaf": "オラフ",
    "Orianna": "オリアナ",
    "Ornn": "オーン",
    "Pantheon": "パンテオン",
    "Poppy": "ポッピー",
    "Pyke": "パイク",
    "Qiyana": "キヤナ",
    "Quinn": "クイン",
    "Rakan": "ラカン",
    "Rammus": "ラムス",
    "Rek'Sai": "レク＝サイ",
    "Rell": "レル",
    "Renata Glasc": "レナータ・グラスク",
    "Renekton": "レネクトン",
    "Rengar": "レンガー",
    "Riven": "リヴェン",
    "Rumble": "ランブル",
    "Ryze": "ライズ",
    "Samira": "サミーラ",
    "Sejuani": "セジュアニ",
    "Senna": "セナ",
    "Seraphine": "セラフィーン",
    "Sett": "セト",
    "Shaco": "シャコ",
    "Shen": "シェン",
    "Shyvana": "シヴァーナ",
    "Singed": "シンジド",
    "Sion": "サイオン",
    "Sivir": "シヴィア",
    "Skarner": "スカーナー",
    "Smolder": "スモルダー",
    "Sona": "ソナ",
    "Soraka": "ソラカ",
    "Swain": "スウェイン",
    "Sylas": "サイラス",
    "Syndra": "シンドラ",
    "Tahm Kench": "タム・ケンチ",
    "Taliyah": "タリヤ",
    "Talon": "タロン",
    "Taric": "タリック",
    "Teemo": "ティーモ",
    "Thresh": "スレッシュ",
    "Tristana": "トリスターナ",
    "Trundle": "トランドル",
    "Tryndamere": "トリンダメア",
    "Twisted Fate": "ツイステッド・フェイト",
    "Twitch": "トゥイッチ",
    "Udyr": "ウディア",
    "Urgot": "アーゴット",
    "Varus": "ヴァルス",
    "Vayne": "ヴェイン",
    "Veigar": "ベイガー",
    "Vel'koz": "ヴェル＝コズ",
    "Vex": "ヴェックス",
    "Vi": "ヴァイ",
    "Viego": "ヴィエゴ",
    "Viktor": "ビクター",
    "Vladimir": "ブラッドミア",
    "Volibear": "ボリベア",
    "Warwick": "ワーウィック",
    "Wukong": "ウーコン",
    "Xayah": "ザヤ",
    "Xerath": "ゼラス",
    "Xin Zhao": "シン・ジャオ",
    "Yasuo": "ヤスオ",
    "Yone": "ヨネ",
    "Yorick": "ヨリック",
    "Yunara": "ユナラ",
    "Yuumi": "ユーミ",
    "Zac": "ザック",
    "Zed": "ゼド",
    "Zeri": "ゼリ",
    "Ziggs": "ジグス",
    "Zilean": "ジリアン",
    "Zoe": "ゾーイ",
    "Zyra": "ザイラ"
}

# 間違った名前 → 正しい名前のマッピング
name_corrections = {
    "アートロックス": "エイトロックス",
    "マスターヤイ": "マスター・イー",
    "エヴリン": "イブリン",
    "ラモス": "ラムス",
    "ズヤ": "ザイラ",
    "ゼヤ": "ザヤ",
    "シャイバナ": "シヴァーナ",
    "カズィックス": "カ＝ジックス",
    "ブリッツクランキング": "ブリッツクランク",
    "ヴィクター": "ビクター",
    "シヴィル": "シヴィア",
    "ズィグス": "ジグス",
    "ビエゴ": "ヴィエゴ",
    "ウォーウィック": "ワーウィック",
    "オーレリオン・ソル": "オレリオン・ソル",
    "ヌヌ": "ヌヌ＆ウィルンプ",
    "ジャーヴァンⅣ": "ジャーヴァンIV",
    "グナー": "ナー",
    "セラフィーヌ": "セラフィーン",
    "サミラ": "サミーラ",
    "コーキー": "コーキ"
}

print("=" * 70)
print("index.htmlのチャンピオン名を公式名に修正します")
print("=" * 70)
print()

# index.htmlを読み込み
with open("index.html", "r", encoding="utf-8") as f:
    content = f.read()

# 修正を適用
corrections_applied = []
for wrong, correct in name_corrections.items():
    count = content.count(wrong)
    if count > 0:
        content = content.replace(wrong, correct)
        corrections_applied.append((wrong, correct, count))
        print(f"✓ {wrong} → {correct} ({count}箇所)")

# 修正後のファイルを保存
with open("index.html", "w", encoding="utf-8") as f:
    f.write(content)

print()
print("=" * 70)
print(f"合計 {len(corrections_applied)} 種類の名前を修正しました")
print("index.html に保存しました")
print("=" * 70)

