[build]
  publish = "."
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

